### ISSUE TITLE
Wow this is really cool

### ISSUE THREAD

**Issue by bindingofisaac** [sauravtom/gitiohack#1]
Can you explain how it works??

**Comment by sauravtom** [comment]
Thanks man :)

So basically, it's a secondary URL redirecting service hosted on GitHub Pages.

  http://google.com ->  http://git.io/hvTe -> http://sauravtom.github.io/4gitiohackRepo?u=http://google.com ->http://google.com

**Comment by bindingofisaac** [comment]
Nice, Neat hack!!

**Comment by saralkochar** [comment]
Nice one :)
